create table veiculo
(
   id bigint generated by default as identity,
   marca varchar (100) not null,
   modelo varchar (100) not null,
   placa varchar (7) not null,
   km_atual double not null,
   tipo_combustivel varchar (8) not null,
   primary key (id)
);

create table veiculo_caminhao
(
   cambio varchar (14) not null,
   tipo varchar (12) not null,
   id bigint not null,
   primary key (id)
);

create table veiculo_carro
(
   cambio varchar (14) not null,
   numero_portas varchar (13) not null,
   tipo varchar (6) not null,
   id bigint not null,
   primary key (id)
);

create table veiculo_moto
(
   cilindrada varchar (6) not null,
   id bigint not null,
   primary key (id)
);

alter table veiculo_caminhao 
add constraint FK_VEICULO_CAMINHAO foreign key (id) references veiculo;

alter table veiculo_carro 
add constraint FK_VEICULO_CARRO foreign key (id) references veiculo;

alter table veiculo_moto 
add constraint FK_VEICULO_MOTO foreign key (id) references veiculo;
